### PR TITLE
Match drag and drop call to action to match theme

### PR DESCRIPTION
**Pull request by voladad**

### CODE REVIEW

**Comment by voladad** [comment]
sorry about it being in 2 requests

**Comment by szero** [comment]
Are you using some kind program for making pull requests? When you fork the repo you can clone it locally with `git clone <url_to_your_fork>`, make your changes, commit them with `git commit -m "change this ya dingus"` and than just do `git push origin master` in order to incorporate them. In order to update the PR you would just commit and push more changes into your fork.

**Comment by voladad** [comment]
yeah i did clone it and tried to push but it gave me a 403 error so i just used the github editor instead

**Comment by szero** [comment]
Cloned your fork or my repo?

**Comment by voladad** [comment]
your repo. probably why it didn't work. i thought i would automatically make the pull request

**Comment by szero** [comment]
Ok, so the procedure is like that: fork my repo -> do changes in your fork -> make a pr -> update your fork if needed as i described above. I will update readme with how to contribute to make it easier.

**Pull request merged**
